language: crystal

install:
  - shards install

script:
  - crystal spec
  - bin/ameba
  - make test-core

os:
  - linux
  - osx

before_deploy:
  - mkdir build
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
    crystal build src/mint.cr -o build/mint-${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME --release;
    else
    crystal build src/mint.cr -o build/mint-${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME --release --static;
    fi

deploy:
  - provider: bintray
    skip_cleanup: true
    user: gdotdesign
    key:
      secure: lueJ8NuexW7k7UeEotqm/k1N/7WY7KGKL3N3b3jMZxybhKa9DsaRy4huRgNL110G+joSSbA55rlQ9XfDO2eRnkao/jwhOygcTIhvjCc2Fs+WOrSLZlVXCp5mweUrcZXvEjGotMc7Un+McVT/tv0b55a9Bb+2xN+FKrJiJf+WTn21BoPzTTOzB4Pspp7iqV7+qjiqLirJ+MObeToYqVlN317GJjaUeTvSwJLMVBsMXWISTd2HS6uXgjvltMXCBjDwg9/BZr20BesfzSGzRpAt8dgzNDm/9wwPOheoFJc6vw3KA/mUX1XhX2lWhwU2QC7hnUmjg2wVrNZQgBq1S2u/wpcElpCF2s79qst7wWW6ZWle9kMVv+CZYR2fpnP3YmKb5PCnx0YB/JmRBnIQXMCWhJmQ9XGaesTv0jwE8qc4/27GvT8dPced9f+vVFRhGHjyPLFR+6Eu6suz/TKwsTcyZD8ZETDClWKICa8hF44PJXW0dGE9kzNwc5bZOUGHj/o6p/X3CC9WuyzZt40O0jnSlFfXs2mT9CTeBM73H7H8j11e7cEPEEUrxZl0bm+V1JYkqo5lZy6n+8JF4zb0kI4xBwtB1IWvboKFetxYr3qpNNvtmighf3kSVtp6HZh0oFKGADUSiRcbGJWiq4CoYu0pes+g357yTI9CtQ5S23Ve2/E=
    file: config/bintray.json
    on:
      branch: master

  - provider: releases
    skip_cleanup: true
    api_key:
      secure: j24NX9YWlWigJ1L5csx+GpbcLBY0RUzD029uFBNGEN9C1nXGIdtXVaxUrd+vCqJf3I40qykKZdajwW8bkt/79KDGDehytDPczP6FKk1NBMR+6usNzgzTMQLg0e7AGn7tVrBRS2cZUaiB6V23K7TNt6O67/jf55CgMsCUXAqycs8TowcXQ7KQvLrN1c2L1X5ypzGgF6Lc484ry9NVsXmr0fcKMJfCaOlJxMhg479GNPwS3EwGs9GrT5STLO+XcssfdFE8ij6eTE7SDtEQgm2MNlysQ6pPbs24k77coC6bVm/KIJMHyResBmOuKRLiY07fEt6LemdxOcfwK59LZCh4ccdawUhI/EhGg6K8QLXeStmRw835pD2juNqfg9Icje1eCkLQJ+6I+FD9QhwRr2ix+yCzVYX3Vfe6wCKqNfnc/kEz/z2UubXrcZeADsOTWIbJXOx0pLue9SnPFXVc/kjp1tUtgQMaZeC8dAhO0Il6miRP5uSEO6Fd/LRFs0LxHoSpbrPLbXggVQd9qm1RKIHaksn8Ajy35DO+vmA0XfXeuAtSlSECsyKXmueGnF+yTXAy/8+S/eKQQbfIAMRUx0SIPKdS86Z5ziWU/afcZNaWWtgI73So88DUG3rPlPwLayV6BpwVxMKbbyDMBOUxWIcZ17orr3KhXVJgpklrFVrdUuU=
    file_glob: true
    file: build/*
    on:
      tags: true

addons:
  firefox: latest
